version: '3'
services:
  front:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: react-uii
    environment:
      - WATCHPACK_POLLING=true
    tty: true
    stdin_open: true
    networks:
      - mern-stack-network
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: node-apii
    restart: always
    networks:
      - mern-stack-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    container_name: mongo-dbi
    networks:
      - mern-stack-network
    volumes:
      - /home/charlestomar0408/mern-dockerized/mongo-backup:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=e-commerce

networks:
  mern-stack-network:
    driver: bridge


